### ISSUE TITLE
Completely incorrect authentication implementation

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#1]
https://github.com/bwsw/tstreams-transaction-server/blob/develop/src/main/scala/com/bwsw/tstreamstransactionserver/netty/server/authService/AuthServiceImpl.scala

Server must have config value:
login = blahblah
password  = secret

Client must submit (login, password) if they are correct then OK, else FAIL.

**Comment by placccebo** [comment]
[fix #1](https://github.com/bwsw/tstreams-transaction-server/commit/532ac886636db6bdfff7a55541c33233e964c787)
