### ISSUE TITLE
Cover commit_log to BerkeleyDB functionality with integration tests and unit tests 

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#10]

**Comment by placccebo** [comment]
test a function - getProcessedCommitLogFiles - of JournaledCommitLogImpl class, whether it returns a list of files sorted by time or not

**Comment by placccebo** [comment]
CommitLogToBerkeleyWriter

**Comment by placccebo** [comment]
rewrite to read one by one transaction from commit log.
remove -> private val recordsToReadNumber = 1000000

**Comment by placccebo** [comment]
TransactionStateHandler

**Comment by placccebo** [comment]
10 hrs

**Comment by placccebo** [comment]
rewrite to read one by one transaction from commit log

**Comment by placccebo** [comment]
CommitLogQueueBootstrapTestSuit, ServerClientInterconnection, TransactionStateHandlerTestSuit
