### ISSUE TITLE
Implement pool for server handler that assigns tasks according to stream and its partition.

### ISSUE THREAD

**Issue by ognelis** [bwsw/tstreams-transaction-server#160]

**Comment by bwsw** [comment]
In constructor of the server there is a parameter **orderedExecutionPoolSize** which is by default should take the value of Runtime.getRuntime().availableProcessors() but can be overriden with parameter (default parameter value if not set is Runtime.getRuntime().availableProcessors() too).

This parameter defines the size of OrdereExecutorPool which is an array of execution context created on ```scala Executors.newSingleThreadExecutor```. Please, not that for debugging purposes every execution service should have unique name like "OrderedExecutionService-$index", where index is array index of that service.
