### ISSUE TITLE
Wrong level of logging

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#26]
Intensive operations must go with DEBUG, not INFO.

ServerPool-0] INFO com.bwsw.tstreamstransactionserver.netty.server.Server - Server processed successfully request putTransaction with id -2147482641 of /127.0.0.1:47137
[ScalaTest-run-running-TransactionDatabaseTests] INFO com.bwsw.tstreamstransactionserver.netty.client.Client - scanTransactions method is invoked.
[epollEventLoopGroup-3-1] INFO com.bwsw.tstreamstransactionserver.netty.server.Server - /127.0.0.1:47137 request scanTransactions with id -2147482640

**Comment by placccebo** [comment]
#21 estimation time
