### ISSUE TITLE
Commit_log processing note: track latest open

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#29]
It's important to ignore when certain open for certain partition and certain stream has delayed timestamp. It's improper behavior and must be handled (all that opens must be dropped, and further events also), e.g.

t1(13, open) - ok
t2(1, open) - drop (out of order)
t1(13, checkpointed) ok
t2(1, checkpointed) - drop (no open->checkpointed transition)

Actually, that behaviour is specified in the: https://github.com/bwsw/t-streams/blob/master/src/main/scala/com/bwsw/tstreams/agents/consumer/subscriber/TransactionBuffer.scala

**Comment by placccebo** [comment]
with tests (2 + 4 hrs)

**Comment by placccebo** [comment]
ref. ServerLastTransactionTestSuit
