### ISSUE TITLE
Handle max transmit message size properly

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#33]
It must be less than 2G AFAIS.
Proper implementation must be the next. In server config it's necessary to define two variables
- maxMetadataPackageSize
- maxDataPackageSize
Both parameters are specified in bytes.

When client authenticates it receives that two parameters togeter with token and uses them to avoid big packages. It's good practice because we can decrease time to process single request.

If **client** tries to transmit amount of data which is greater than maxMetadataPackageSize or maxDataPackageSize then it gets exception PackageTooBigException (It's about client check after serialization). When client receives packages it doesn't check for validity.

If **server** receives client requests of size which is greater than defined in constants then it discards them and sends PackageTooBigException to the client.

**Comment by placccebo** [comment]
2 hrs

**Comment by placccebo** [comment]
3373 merged into develop
