### ISSUE TITLE
ScanTransactions* Improvement

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#50]
This proposal relates to TTS implementation which uses commit_log functionality. When commit_log is used the main problem is that the metadata become available for read access late (after commit_log is processed). This causes different potential problems. In a nutshell we have to differentiate two different situations - data absent or data incomplete. The first one is a normal situation which means that there are no requested elements for sure, but the second one means that we still don't know if there are data or no.

scanTransactions method must give an client means to recognize the result. Right now (in pure BDB implementation) it returns just Seq of transactions and that's why we can not differentiate (Nil, incomplete) from (Nil, absent), so the method must be modified to 

`scanTransactionsForward(..., predicate): (Boolean, Seq)`
`scanTransactionsBackward(..., predicate): (Boolean, Seq)`

because this give a client an idea what's going on. The method must function in the next way:

1st - we have to track last transaction per partition in BDB and in RAM, this value is updated when commit log is processed, so we keep max(transactionid) for every (stream, partition). Later I will call it **LT**.

2nd - when the system handles scanTransactions(A, B) it must consider 3 cases:

1. LT < A: return (false, Nil)
2. A <= LT < B: return (false, AvailableTransactions[A, LT]
3. LT >= B: (true, AvailableTransactions[A, B])

As a side effect it's possible to implement a request getLastTransaction(stream, partition) which is to be done.

If **server** during it's operation **undertands** that it'is near to overfill constraints it can stop operation and return partial dataset. This is specific to scanTransactions and getTransactionData operations. So it can return pair (boolean, resultSet) where boolean is true if request was completed or false if response is partial. #33

**Comment by placccebo** [comment]
10 hrs
