### ISSUE TITLE
getTransaction implementation

### ISSUE THREAD

**Issue by bwsw** [bwsw/tstreams-transaction-server#52]
getTransaction must be implemented according to #50. See it first. To implement it properly the method must have following signature:

`getTransaction(stream, partition, transaction): (boolean, Data)` 

where
1. `(false, None)` means that the transaction is not ready yet transactionID > LT
2. `(true, Some(Data))` means that the transaction is found
3. `(true, None)` means that the transaction does not exist.

**Comment by placccebo** [comment]
4 hrs
