### ISSUE TITLE
Develop more complex integration and unit tests for transaction server and client.

### ISSUE THREAD

**Issue by ognelis** [bwsw/tstreams-transaction-server#71]

**Comment by placccebo** [comment]
add a test suit for getLastCheckpointedTransaction method

**Comment by placccebo** [comment]
remove unused variables from tests (I found minTransactionID or maxTransactionID )

**Comment by placccebo** [comment]
ServerScanTransactionsTest should contain two tests that check successful and unsuccessful filtering with lambda

**Comment by placccebo** [comment]
ManyClientsServerInterconnectionTest - check a case when one client opens a txn and another client closes this txn. After that both of clients should get the same txn

**Comment by placccebo** [comment]
ManyClientsServerInterconnectionTest - add a test: "One client" should "put transaction data, another one should put the data for which a "from" value equals the previous "to" value, and both clients should get the concatenation of this data."
