### ISSUE TITLE
Develop a method PutTransaction that persists producer and consumer transaction or producer transaction with it's data.

### ISSUE THREAD

**Issue by ognelis** [bwsw/tstreams-transaction-server#9]

**Comment by bwsw** [comment]
I don't think the title is correct. It's better to split on
- putConsumerCheckpoint
- putProducerTransactionState(state [transaction data])

**Comment by bwsw** [comment]
See  #30

**Comment by placccebo** [comment]
1. remove putTransaction(consumerTransaction)
2. add putConsumerCheckpoint(stream, part, consumer, transactionID)
3. rename putTransactionData (txn, data) -> putProducerStateWithData - state & data
4. putProducerState - just state
5. putTransactionData - just data

**Comment by placccebo** [comment]
2 hrs
